project_id = "fkcszgrewzhswdtsqpad"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.check-subscription]
    verify_jwt = false
  [functions.create-checkout]
    verify_jwt = false
  [functions.create-payment]
    verify_jwt = false
  [functions.customer-portal]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = false
  [functions.send-transactional-email]
    verify_jwt = false
  [functions.stripe-webhook]
    verify_jwt = false
