project_id = "fkcszgrewzhswdtsqpad"

[functions]
  [functions.admin-delete-user]
    verify_jwt = false
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.check-subscription]
    verify_jwt = false
  [functions.create-checkout]
    verify_jwt = false
  [functions.create-payment]
    verify_jwt = false
  [functions.customer-portal]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-transactional-email]
    verify_jwt = false
  [functions.sync-inventory]
    verify_jwt = false
  [functions.stripe-webhook]
    verify_jwt = false
  [functions.create-seller-checkout]
    verify_jwt = false
  [functions.seller-stripe-webhook]
    verify_jwt = false
  [functions.seller-preauth]
    verify_jwt = false
